{"name": "test_register_user[\\u6d4b\\u8bd5test-123456-13599999999-3-\\u6df1\\u5733\\u5e02\\u5b9d\\u5b89\\u533a-False-2003-\\u8f93\\u5165\\u7684\\u6027\\u522b\\u53ea\\u80fd\\u662f 0(\\u7537) \\u6216 1(\\u5973)]", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'iter_parents'", "trace": "self = <allure_pytest.listener.AllureListener object at 0x10b32e3a0>\nitem = <Function test_register_user[\\u6d4b\\u8bd5test-123456-13599999999-3-\\u6df1\\u5733\\u5e02\\u5b9d\\u5b89\\u533a-False-2003-\\u8f93\\u5165\\u7684\\u6027\\u522b\\u53ea\\u80fd\\u662f 0(\\u7537) \\u6216 1(\\u5973)]>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_runtest_setup(self, item):\n        if not self._cache.get(item.nodeid):\n            uuid = self._cache.push(item.nodeid)\n            test_result = TestResult(name=item.name, uuid=uuid, start=now(), stop=now())\n            self.allure_logger.schedule_test(uuid, test_result)\n    \n        yield\n    \n        uuid = self._cache.get(item.nodeid)\n        test_result = self.allure_logger.get_test(uuid)\n>       for fixturedef in _test_fixtures(item):\n\nvenv/lib/python3.8/site-packages/allure_pytest/listener.py:79: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nitem = <Function test_register_user[\\u6d4b\\u8bd5test-123456-13599999999-3-\\u6df1\\u5733\\u5e02\\u5b9d\\u5b89\\u533a-False-2003-\\u8f93\\u5165\\u7684\\u6027\\u522b\\u53ea\\u80fd\\u662f 0(\\u7537) \\u6216 1(\\u5973)]>\n\n    def _test_fixtures(item):\n        fixturemanager = item.session._fixturemanager\n        fixturedefs = []\n    \n        if hasattr(item, \"fixturenames\"):\n            for name in item.fixturenames:\n>               fixturedef = fixturemanager.getfixturedefs(name, item.nodeid)\nE               AttributeError: 'str' object has no attribute 'iter_parents'\n\nvenv/lib/python3.8/site-packages/allure_pytest/listener.py:279: AttributeError"}, "start": 1735908717172, "stop": 1735908717172, "uuid": "3151764d-b136-41fd-90a8-a522ad32d582", "labels": [{"name": "story", "value": "用例--注册用户信息"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户注册模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_02_register"}, {"name": "subSuite", "value": "TestUserRegister"}, {"name": "host", "value": "zhouqideMBP.lan"}, {"name": "thread", "value": "4802-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_02_register"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}